version: "2.7"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: "php /var/app/artisan workflow:init"

temporal:
  address: ${TEMPORAL_CLI_ADDRESS}
  activities:
    num_workers: 4

logs:
  level: debug
  mode: development
